name: Medication Reminder Bot

on:
  schedule:
    # Times configured for 9:00 AM, 2:00 PM, and 9:45 PM UTC
    - cron: '0 9 * * *'    # Morning reminder
    - cron: '30 13 * * *'   # Afternoon reminder
    - cron: '45 21 * * *'  # Evening reminder

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Run Medication Reminder Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python medication_reminder_bot.py
