name: Medication Reminder Bot

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST (4:30 AM UTC) - Morning Reminder
    - cron: '25 7 * * *'   # 12:55 PM IST (7:25 AM UTC) - Afternoon Reminder
    - cron: '45 12 * * *'  # 9:20 PM IST (3:50 PM UTC) - Evening Reminder

jobs:
  morning-reminder:
    if: github.event.schedule == '30 4 * * *'   # Run only at 10:00 AM IST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Send Morning Reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE_INDEX: 0
        run: python medication_reminder_bot.py

  afternoon-reminder:
    if: github.event.schedule == '25 7 * * *'   # Run only at 12:55 PM IST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Send Afternoon Reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE_INDEX: 1
        run: python medication_reminder_bot.py

  evening-reminder:
    if: github.event.schedule == '50 15 * * *'  # Run only at 9:20 PM IST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Send Evening Reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE_INDEX: 2
        run: python medication_reminder_bot.py
