name: Medication Reminder Bot

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST (4:30 AM UTC) - Morning
    - cron: '30 10 * * *'   # 1:00 PM IST (7:30 AM UTC) - Afternoon
    - cron: '30 15 * * *'  # 9:00 PM IST (3:30 PM UTC) - Evening

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message_index: [0, 1, 2]  # Indices for morning, afternoon, and evening messages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Run Medication Reminder Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MESSAGE_INDEX: ${{ matrix.message_index }}
      run: python medication_reminder_bot.py
